# Generated by Django 4.2.4 on 2023-09-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=200)),
                ('vehicle_number', models.CharField(max_length=200)),
                ('vehicle_model', models.CharField(max_length=200)),
                ('owner_name', models.CharField(max_length=200)),
                ('kms_run', models.PositiveIntegerField()),
                ('image', models.ImageField(null=True, upload_to='images')),
            ],
        ),
    ]
